
package irrgarten.UI;

import irrgarten.Directions;

public class Cursors extends javax.swing.JDialog {
    
    private Directions direction;
        
    public Cursors(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
        
    public Directions getDirection() {
        setVisible(true);   // Hace visible la ventana y bloquea la ejecución hasta que se cierre
        return this.direction;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UPbutton = new javax.swing.JButton();
        LEFTbutton = new javax.swing.JButton();
        RIGHTbutton = new javax.swing.JButton();
        DOWNbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        UPbutton.setText("UP");
        UPbutton.addActionListener(this::UPbuttonActionPerformed);

        LEFTbutton.setText("LEFT");
        LEFTbutton.addActionListener(this::LEFTbuttonActionPerformed);

        RIGHTbutton.setText("RIGHT");
        RIGHTbutton.addActionListener(this::RIGHTbuttonActionPerformed);

        DOWNbutton.setText("DOWN");
        DOWNbutton.addActionListener(this::DOWNbuttonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LEFTbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RIGHTbutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UPbutton)
                            .addComponent(DOWNbutton))
                        .addGap(0, 127, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(UPbutton)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LEFTbutton)
                    .addComponent(RIGHTbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(DOWNbutton)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UPbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPbuttonActionPerformed
        // 1. Guardar la dirección elegida en el atributo 'direction'
        direction = Directions.UP; 

        // 2. Ejecutar el método dispose para cerrar el diálogo
        dispose();  
    }//GEN-LAST:event_UPbuttonActionPerformed

    private void DOWNbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOWNbuttonActionPerformed
        // 1. Guardar la dirección elegida en el atributo 'direction'
        direction = Directions.DOWN; 

        // 2. Ejecutar el método dispose para cerrar el diálogo
        dispose();
    }//GEN-LAST:event_DOWNbuttonActionPerformed

    private void LEFTbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LEFTbuttonActionPerformed
        // 1. Guardar la dirección elegida en el atributo 'direction'
        direction = Directions.LEFT; 

        // 2. Ejecutar el método dispose para cerrar el diálogo
        dispose();
    }//GEN-LAST:event_LEFTbuttonActionPerformed

    private void RIGHTbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RIGHTbuttonActionPerformed
        // 1. Guardar la dirección elegida en el atributo 'direction'
        direction = Directions.RIGHT; 

        // 2. Ejecutar el método dispose para cerrar el diálogo
        dispose();
    }//GEN-LAST:event_RIGHTbuttonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DOWNbutton;
    private javax.swing.JButton LEFTbutton;
    private javax.swing.JButton RIGHTbutton;
    private javax.swing.JButton UPbutton;
    // End of variables declaration//GEN-END:variables
}
