
package irrgarten.UI;


import irrgarten.Directions;
import irrgarten.GameState;


public class GraphicUI extends javax.swing.JFrame implements UI{
    

    private Cursors cursor;
    
    /**
     * Creates new form GraphicUI
     */
    public GraphicUI() {
        initComponents();

        // Primer parámetro: referencia al propio JFrame
        // Segundo parámetro: activa el modo modal, para que el cuadro de diálogo no ceda el foco mientras esté abierto.
        cursor = new Cursors(this, true);

        setVisible(true); // Para que la ventana de la aplicación sea visible.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        laberinto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        jugador_actual = new javax.swing.JLabel();
        ganador = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        monsters_players = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        laberinto.setColumns(20);
        laberinto.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        laberinto.setRows(5);
        jScrollPane1.setViewportView(laberinto);

        log.setColumns(20);
        log.setRows(5);
        jScrollPane2.setViewportView(log);

        jugador_actual.setText("jLabel1");

        ganador.setText("jLabel2");

        monsters_players.setColumns(20);
        monsters_players.setRows(5);
        jScrollPane3.setViewportView(monsters_players);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jugador_actual)
                            .addComponent(ganador)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jugador_actual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ganador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ganador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jugador_actual;
    private javax.swing.JTextArea laberinto;
    private javax.swing.JTextArea log;
    private javax.swing.JTextArea monsters_players;
    // End of variables declaration//GEN-END:variables

    @Override
    public Directions nextMove() {
        return cursor.getDirection(); // Delega en el cuadro de diálogo comunicación con el usuario
    }
    
    
    @Override
    public void showGame(GameState gameState){

        String estadoJuego =  "\n\n--- MONSTERS ---\n" + gameState.getMonsters() + "\n\n--- PLAYERS ---\n" + gameState.getPlayers();

        this.monsters_players.setText(estadoJuego);
        this.laberinto.setText(gameState.getLabyrinth());

        this.log.setText(gameState.getLog());

        this.jugador_actual.setText("Current player: " + gameState.getCurrentPlayer());

        if (gameState.getWinner()) {
            this.ganador.setText("Winner: Player " + gameState.getCurrentPlayer() + "!");
            this.ganador.setVisible(true);
        } else {
            this.ganador.setVisible(false);
        }
    
    repaint(); // Para actualizar la interfaz gráfica
    }
    

}
